### ISSUE TITLE
Jak przetwarzamy dane?

### ISSUE THREAD

**Issue by Toumash** [AlicjaDobrzeniecka/mindy#18]
Alicja chce robić ML w pythonie, wiec pytanie jak to ogarnąć na firebase?

**Comment by efemeryds** [comment]
potrzebuję pobierać dane z bazy, przetworzyć je w pythonie (zrobimy ML interpolacja i rekomendacja), zapisać do bazy, wczytać i wyświetlić w JS d3

**Comment by Toumash** [comment]
Nie zdążymy niestety, wypada z milestona
