### ISSUE TITLE
Mock: Logowanie

### ISSUE THREAD

**Issue by Toumash** [AlicjaDobrzeniecka/mindy#2]
![screen1](https://user-images.githubusercontent.com/26259455/78386099-3f649500-75dd-11ea-8226-4981ec395193.png)

**Comment by AlicjaDobrzeniecka** [comment]
![screen1](https://user-images.githubusercontent.com/26259455/78386051-2825a780-75dd-11ea-9a22-485d89c2890c.png)

**Comment by Toumash** [comment]
https://github.com/AlicjaDobrzeniecka/mindy/commit/6789102b0042ee24e93dcaffda72a1e4469ddf3e
