### ISSUE TITLE
kolor separatorów 3 kategori na niebiesko

### ISSUE THREAD

**Issue by efemeryds** [AlicjaDobrzeniecka/mindy#48]
![image](https://user-images.githubusercontent.com/26259455/78463224-9ac87d00-76da-11ea-83a0-07290367a7b2.png)

**Comment by Toumash** [comment]
Do zmiany kolor pasków z ss w taskach, topicach i relaxie na kolor z logowania #cce6ff

**Comment by Toumash** [comment]
done https://github.com/AlicjaDobrzeniecka/mindy/commit/86ff050b1ef58b275e28f26148dfbbbe91714d76
